# Site settings
name: 卑微程序员的惨痛历程
email: subenlele@gmail.com
author: 粟粞
url: http://subenle.com
resume_site: https://github.com/Subenle
github: https://github.com/Subenle
baseurl: ""
description: 日常学习、debug问题小记
meta_description: 个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: subenle

# Build settings
markdown: kramdown

baidu_analysis: 808d5e953ce182fff59ba3020d92d06b

